command:
  - streamlit
  - run
  - app.py
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
    value: "false"
